// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storehouse.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Storehouse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CityId               int32    `protobuf:"varint,3,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Storehouse) Reset()         { *m = Storehouse{} }
func (m *Storehouse) String() string { return proto.CompactTextString(m) }
func (*Storehouse) ProtoMessage()    {}
func (*Storehouse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{0}
}

func (m *Storehouse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storehouse.Unmarshal(m, b)
}
func (m *Storehouse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storehouse.Marshal(b, m, deterministic)
}
func (m *Storehouse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storehouse.Merge(m, src)
}
func (m *Storehouse) XXX_Size() int {
	return xxx_messageInfo_Storehouse.Size(m)
}
func (m *Storehouse) XXX_DiscardUnknown() {
	xxx_messageInfo_Storehouse.DiscardUnknown(m)
}

var xxx_messageInfo_Storehouse proto.InternalMessageInfo

func (m *Storehouse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Storehouse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Storehouse) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type StorehouseItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StorehouseId         int32    `protobuf:"varint,2,opt,name=storehouse_id,json=storehouseId,proto3" json:"storehouse_id,omitempty"`
	ComponentId          int32    `protobuf:"varint,3,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorehouseItem) Reset()         { *m = StorehouseItem{} }
func (m *StorehouseItem) String() string { return proto.CompactTextString(m) }
func (*StorehouseItem) ProtoMessage()    {}
func (*StorehouseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{1}
}

func (m *StorehouseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorehouseItem.Unmarshal(m, b)
}
func (m *StorehouseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorehouseItem.Marshal(b, m, deterministic)
}
func (m *StorehouseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorehouseItem.Merge(m, src)
}
func (m *StorehouseItem) XXX_Size() int {
	return xxx_messageInfo_StorehouseItem.Size(m)
}
func (m *StorehouseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StorehouseItem.DiscardUnknown(m)
}

var xxx_messageInfo_StorehouseItem proto.InternalMessageInfo

func (m *StorehouseItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StorehouseItem) GetStorehouseId() int32 {
	if m != nil {
		return m.StorehouseId
	}
	return 0
}

func (m *StorehouseItem) GetComponentId() int32 {
	if m != nil {
		return m.ComponentId
	}
	return 0
}

func (m *StorehouseItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateStorehouseRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CityId               int32    `protobuf:"varint,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStorehouseRequest) Reset()         { *m = CreateStorehouseRequest{} }
func (m *CreateStorehouseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStorehouseRequest) ProtoMessage()    {}
func (*CreateStorehouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{2}
}

func (m *CreateStorehouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStorehouseRequest.Unmarshal(m, b)
}
func (m *CreateStorehouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStorehouseRequest.Marshal(b, m, deterministic)
}
func (m *CreateStorehouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStorehouseRequest.Merge(m, src)
}
func (m *CreateStorehouseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStorehouseRequest.Size(m)
}
func (m *CreateStorehouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStorehouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStorehouseRequest proto.InternalMessageInfo

func (m *CreateStorehouseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateStorehouseRequest) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type CreateStorehouseResponse struct {
	Result               *Storehouse `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateStorehouseResponse) Reset()         { *m = CreateStorehouseResponse{} }
func (m *CreateStorehouseResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStorehouseResponse) ProtoMessage()    {}
func (*CreateStorehouseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{3}
}

func (m *CreateStorehouseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStorehouseResponse.Unmarshal(m, b)
}
func (m *CreateStorehouseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStorehouseResponse.Marshal(b, m, deterministic)
}
func (m *CreateStorehouseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStorehouseResponse.Merge(m, src)
}
func (m *CreateStorehouseResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStorehouseResponse.Size(m)
}
func (m *CreateStorehouseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStorehouseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStorehouseResponse proto.InternalMessageInfo

func (m *CreateStorehouseResponse) GetResult() *Storehouse {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetStorehousesListByCityIdRequest struct {
	CityId               int32    `protobuf:"varint,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStorehousesListByCityIdRequest) Reset()         { *m = GetStorehousesListByCityIdRequest{} }
func (m *GetStorehousesListByCityIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetStorehousesListByCityIdRequest) ProtoMessage()    {}
func (*GetStorehousesListByCityIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{4}
}

func (m *GetStorehousesListByCityIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehousesListByCityIdRequest.Unmarshal(m, b)
}
func (m *GetStorehousesListByCityIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehousesListByCityIdRequest.Marshal(b, m, deterministic)
}
func (m *GetStorehousesListByCityIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehousesListByCityIdRequest.Merge(m, src)
}
func (m *GetStorehousesListByCityIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetStorehousesListByCityIdRequest.Size(m)
}
func (m *GetStorehousesListByCityIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehousesListByCityIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehousesListByCityIdRequest proto.InternalMessageInfo

func (m *GetStorehousesListByCityIdRequest) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type GetStorehouseItemsByStorehouseIdRequest struct {
	StorehouseId         int32    `protobuf:"varint,1,opt,name=storehouse_id,json=storehouseId,proto3" json:"storehouse_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStorehouseItemsByStorehouseIdRequest) Reset() {
	*m = GetStorehouseItemsByStorehouseIdRequest{}
}
func (m *GetStorehouseItemsByStorehouseIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetStorehouseItemsByStorehouseIdRequest) ProtoMessage()    {}
func (*GetStorehouseItemsByStorehouseIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{5}
}

func (m *GetStorehouseItemsByStorehouseIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdRequest.Unmarshal(m, b)
}
func (m *GetStorehouseItemsByStorehouseIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdRequest.Marshal(b, m, deterministic)
}
func (m *GetStorehouseItemsByStorehouseIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehouseItemsByStorehouseIdRequest.Merge(m, src)
}
func (m *GetStorehouseItemsByStorehouseIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdRequest.Size(m)
}
func (m *GetStorehouseItemsByStorehouseIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehouseItemsByStorehouseIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehouseItemsByStorehouseIdRequest proto.InternalMessageInfo

func (m *GetStorehouseItemsByStorehouseIdRequest) GetStorehouseId() int32 {
	if m != nil {
		return m.StorehouseId
	}
	return 0
}

type GetStorehousesListResponse struct {
	Result               []*Storehouse `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetStorehousesListResponse) Reset()         { *m = GetStorehousesListResponse{} }
func (m *GetStorehousesListResponse) String() string { return proto.CompactTextString(m) }
func (*GetStorehousesListResponse) ProtoMessage()    {}
func (*GetStorehousesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{6}
}

func (m *GetStorehousesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehousesListResponse.Unmarshal(m, b)
}
func (m *GetStorehousesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehousesListResponse.Marshal(b, m, deterministic)
}
func (m *GetStorehousesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehousesListResponse.Merge(m, src)
}
func (m *GetStorehousesListResponse) XXX_Size() int {
	return xxx_messageInfo_GetStorehousesListResponse.Size(m)
}
func (m *GetStorehousesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehousesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehousesListResponse proto.InternalMessageInfo

func (m *GetStorehousesListResponse) GetResult() []*Storehouse {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetStorehouseItemByIdRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStorehouseItemByIdRequest) Reset()         { *m = GetStorehouseItemByIdRequest{} }
func (m *GetStorehouseItemByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetStorehouseItemByIdRequest) ProtoMessage()    {}
func (*GetStorehouseItemByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{7}
}

func (m *GetStorehouseItemByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehouseItemByIdRequest.Unmarshal(m, b)
}
func (m *GetStorehouseItemByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehouseItemByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetStorehouseItemByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehouseItemByIdRequest.Merge(m, src)
}
func (m *GetStorehouseItemByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetStorehouseItemByIdRequest.Size(m)
}
func (m *GetStorehouseItemByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehouseItemByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehouseItemByIdRequest proto.InternalMessageInfo

func (m *GetStorehouseItemByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetStorehouseItemByIdResponse struct {
	Result               *StorehouseItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetStorehouseItemByIdResponse) Reset()         { *m = GetStorehouseItemByIdResponse{} }
func (m *GetStorehouseItemByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetStorehouseItemByIdResponse) ProtoMessage()    {}
func (*GetStorehouseItemByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{8}
}

func (m *GetStorehouseItemByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehouseItemByIdResponse.Unmarshal(m, b)
}
func (m *GetStorehouseItemByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehouseItemByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetStorehouseItemByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehouseItemByIdResponse.Merge(m, src)
}
func (m *GetStorehouseItemByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetStorehouseItemByIdResponse.Size(m)
}
func (m *GetStorehouseItemByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehouseItemByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehouseItemByIdResponse proto.InternalMessageInfo

func (m *GetStorehouseItemByIdResponse) GetResult() *StorehouseItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest struct {
	StorehouseId         int32    `protobuf:"varint,1,opt,name=storehouse_id,json=storehouseId,proto3" json:"storehouse_id,omitempty"`
	ComponentIds         []int32  `protobuf:"varint,2,rep,packed,name=component_ids,json=componentIds,proto3" json:"component_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) Reset() {
	*m = GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest{}
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) String() string {
	return proto.CompactTextString(m)
}
func (*GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) ProtoMessage() {}
func (*GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{9}
}

func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest.Unmarshal(m, b)
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest.Marshal(b, m, deterministic)
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest.Merge(m, src)
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest.Size(m)
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest proto.InternalMessageInfo

func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) GetStorehouseId() int32 {
	if m != nil {
		return m.StorehouseId
	}
	return 0
}

func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) GetComponentIds() []int32 {
	if m != nil {
		return m.ComponentIds
	}
	return nil
}

type GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse struct {
	Result               []*StorehouseItem `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) Reset() {
	*m = GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse{}
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) String() string {
	return proto.CompactTextString(m)
}
func (*GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) ProtoMessage() {}
func (*GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{10}
}

func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse.Unmarshal(m, b)
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse.Marshal(b, m, deterministic)
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse.Merge(m, src)
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) XXX_Size() int {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse.Size(m)
}
func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse proto.InternalMessageInfo

func (m *GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse) GetResult() []*StorehouseItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetStorehouseItemsByStorehouseIdResponse struct {
	Result               []*StorehouseItem `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetStorehouseItemsByStorehouseIdResponse) Reset() {
	*m = GetStorehouseItemsByStorehouseIdResponse{}
}
func (m *GetStorehouseItemsByStorehouseIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetStorehouseItemsByStorehouseIdResponse) ProtoMessage()    {}
func (*GetStorehouseItemsByStorehouseIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{11}
}

func (m *GetStorehouseItemsByStorehouseIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdResponse.Unmarshal(m, b)
}
func (m *GetStorehouseItemsByStorehouseIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdResponse.Marshal(b, m, deterministic)
}
func (m *GetStorehouseItemsByStorehouseIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehouseItemsByStorehouseIdResponse.Merge(m, src)
}
func (m *GetStorehouseItemsByStorehouseIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetStorehouseItemsByStorehouseIdResponse.Size(m)
}
func (m *GetStorehouseItemsByStorehouseIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehouseItemsByStorehouseIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehouseItemsByStorehouseIdResponse proto.InternalMessageInfo

func (m *GetStorehouseItemsByStorehouseIdResponse) GetResult() []*StorehouseItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateStorehouseItemForStorehoseRequest struct {
	ComponentId          int32    `protobuf:"varint,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	StorehouseId         int32    `protobuf:"varint,2,opt,name=storehouse_id,json=storehouseId,proto3" json:"storehouse_id,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStorehouseItemForStorehoseRequest) Reset() {
	*m = CreateStorehouseItemForStorehoseRequest{}
}
func (m *CreateStorehouseItemForStorehoseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStorehouseItemForStorehoseRequest) ProtoMessage()    {}
func (*CreateStorehouseItemForStorehoseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{12}
}

func (m *CreateStorehouseItemForStorehoseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStorehouseItemForStorehoseRequest.Unmarshal(m, b)
}
func (m *CreateStorehouseItemForStorehoseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStorehouseItemForStorehoseRequest.Marshal(b, m, deterministic)
}
func (m *CreateStorehouseItemForStorehoseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStorehouseItemForStorehoseRequest.Merge(m, src)
}
func (m *CreateStorehouseItemForStorehoseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStorehouseItemForStorehoseRequest.Size(m)
}
func (m *CreateStorehouseItemForStorehoseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStorehouseItemForStorehoseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStorehouseItemForStorehoseRequest proto.InternalMessageInfo

func (m *CreateStorehouseItemForStorehoseRequest) GetComponentId() int32 {
	if m != nil {
		return m.ComponentId
	}
	return 0
}

func (m *CreateStorehouseItemForStorehoseRequest) GetStorehouseId() int32 {
	if m != nil {
		return m.StorehouseId
	}
	return 0
}

func (m *CreateStorehouseItemForStorehoseRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateStorehouseItemResponse struct {
	Result               *StorehouseItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateStorehouseItemResponse) Reset()         { *m = CreateStorehouseItemResponse{} }
func (m *CreateStorehouseItemResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStorehouseItemResponse) ProtoMessage()    {}
func (*CreateStorehouseItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{13}
}

func (m *CreateStorehouseItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStorehouseItemResponse.Unmarshal(m, b)
}
func (m *CreateStorehouseItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStorehouseItemResponse.Marshal(b, m, deterministic)
}
func (m *CreateStorehouseItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStorehouseItemResponse.Merge(m, src)
}
func (m *CreateStorehouseItemResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStorehouseItemResponse.Size(m)
}
func (m *CreateStorehouseItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStorehouseItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStorehouseItemResponse proto.InternalMessageInfo

func (m *CreateStorehouseItemResponse) GetResult() *StorehouseItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateStorehouseItemRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStorehouseItemRequest) Reset()         { *m = UpdateStorehouseItemRequest{} }
func (m *UpdateStorehouseItemRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStorehouseItemRequest) ProtoMessage()    {}
func (*UpdateStorehouseItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{14}
}

func (m *UpdateStorehouseItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStorehouseItemRequest.Unmarshal(m, b)
}
func (m *UpdateStorehouseItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStorehouseItemRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStorehouseItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStorehouseItemRequest.Merge(m, src)
}
func (m *UpdateStorehouseItemRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStorehouseItemRequest.Size(m)
}
func (m *UpdateStorehouseItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStorehouseItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStorehouseItemRequest proto.InternalMessageInfo

func (m *UpdateStorehouseItemRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateStorehouseItemRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type UpdateStorehouseItemResponse struct {
	Result               *StorehouseItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateStorehouseItemResponse) Reset()         { *m = UpdateStorehouseItemResponse{} }
func (m *UpdateStorehouseItemResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateStorehouseItemResponse) ProtoMessage()    {}
func (*UpdateStorehouseItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{15}
}

func (m *UpdateStorehouseItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStorehouseItemResponse.Unmarshal(m, b)
}
func (m *UpdateStorehouseItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStorehouseItemResponse.Marshal(b, m, deterministic)
}
func (m *UpdateStorehouseItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStorehouseItemResponse.Merge(m, src)
}
func (m *UpdateStorehouseItemResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateStorehouseItemResponse.Size(m)
}
func (m *UpdateStorehouseItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStorehouseItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStorehouseItemResponse proto.InternalMessageInfo

func (m *UpdateStorehouseItemResponse) GetResult() *StorehouseItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteStorehouseRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorehouseRequest) Reset()         { *m = DeleteStorehouseRequest{} }
func (m *DeleteStorehouseRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStorehouseRequest) ProtoMessage()    {}
func (*DeleteStorehouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{16}
}

func (m *DeleteStorehouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorehouseRequest.Unmarshal(m, b)
}
func (m *DeleteStorehouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorehouseRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStorehouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorehouseRequest.Merge(m, src)
}
func (m *DeleteStorehouseRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStorehouseRequest.Size(m)
}
func (m *DeleteStorehouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorehouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorehouseRequest proto.InternalMessageInfo

func (m *DeleteStorehouseRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteStorehouseResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorehouseResponse) Reset()         { *m = DeleteStorehouseResponse{} }
func (m *DeleteStorehouseResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStorehouseResponse) ProtoMessage()    {}
func (*DeleteStorehouseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{17}
}

func (m *DeleteStorehouseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorehouseResponse.Unmarshal(m, b)
}
func (m *DeleteStorehouseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorehouseResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStorehouseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorehouseResponse.Merge(m, src)
}
func (m *DeleteStorehouseResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStorehouseResponse.Size(m)
}
func (m *DeleteStorehouseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorehouseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorehouseResponse proto.InternalMessageInfo

type DeleteStorehousesByCityIdRequest struct {
	CityIds              []int32  `protobuf:"varint,1,rep,packed,name=city_ids,json=cityIds,proto3" json:"city_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorehousesByCityIdRequest) Reset()         { *m = DeleteStorehousesByCityIdRequest{} }
func (m *DeleteStorehousesByCityIdRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStorehousesByCityIdRequest) ProtoMessage()    {}
func (*DeleteStorehousesByCityIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{18}
}

func (m *DeleteStorehousesByCityIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorehousesByCityIdRequest.Unmarshal(m, b)
}
func (m *DeleteStorehousesByCityIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorehousesByCityIdRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStorehousesByCityIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorehousesByCityIdRequest.Merge(m, src)
}
func (m *DeleteStorehousesByCityIdRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStorehousesByCityIdRequest.Size(m)
}
func (m *DeleteStorehousesByCityIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorehousesByCityIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorehousesByCityIdRequest proto.InternalMessageInfo

func (m *DeleteStorehousesByCityIdRequest) GetCityIds() []int32 {
	if m != nil {
		return m.CityIds
	}
	return nil
}

type DeleteStorehousesByCityIdResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorehousesByCityIdResponse) Reset()         { *m = DeleteStorehousesByCityIdResponse{} }
func (m *DeleteStorehousesByCityIdResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStorehousesByCityIdResponse) ProtoMessage()    {}
func (*DeleteStorehousesByCityIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{19}
}

func (m *DeleteStorehousesByCityIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorehousesByCityIdResponse.Unmarshal(m, b)
}
func (m *DeleteStorehousesByCityIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorehousesByCityIdResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStorehousesByCityIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorehousesByCityIdResponse.Merge(m, src)
}
func (m *DeleteStorehousesByCityIdResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStorehousesByCityIdResponse.Size(m)
}
func (m *DeleteStorehousesByCityIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorehousesByCityIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorehousesByCityIdResponse proto.InternalMessageInfo

type DeleteStorehouseItemRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorehouseItemRequest) Reset()         { *m = DeleteStorehouseItemRequest{} }
func (m *DeleteStorehouseItemRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStorehouseItemRequest) ProtoMessage()    {}
func (*DeleteStorehouseItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{20}
}

func (m *DeleteStorehouseItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorehouseItemRequest.Unmarshal(m, b)
}
func (m *DeleteStorehouseItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorehouseItemRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStorehouseItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorehouseItemRequest.Merge(m, src)
}
func (m *DeleteStorehouseItemRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStorehouseItemRequest.Size(m)
}
func (m *DeleteStorehouseItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorehouseItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorehouseItemRequest proto.InternalMessageInfo

func (m *DeleteStorehouseItemRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteStorehouseItemsByComponentIdsRequest struct {
	StorehouseId         int32    `protobuf:"varint,1,opt,name=storehouse_id,json=storehouseId,proto3" json:"storehouse_id,omitempty"`
	ComponentIds         []int32  `protobuf:"varint,2,rep,packed,name=componentIds,proto3" json:"componentIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorehouseItemsByComponentIdsRequest) Reset() {
	*m = DeleteStorehouseItemsByComponentIdsRequest{}
}
func (m *DeleteStorehouseItemsByComponentIdsRequest) String() string {
	return proto.CompactTextString(m)
}
func (*DeleteStorehouseItemsByComponentIdsRequest) ProtoMessage() {}
func (*DeleteStorehouseItemsByComponentIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{21}
}

func (m *DeleteStorehouseItemsByComponentIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorehouseItemsByComponentIdsRequest.Unmarshal(m, b)
}
func (m *DeleteStorehouseItemsByComponentIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorehouseItemsByComponentIdsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStorehouseItemsByComponentIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorehouseItemsByComponentIdsRequest.Merge(m, src)
}
func (m *DeleteStorehouseItemsByComponentIdsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStorehouseItemsByComponentIdsRequest.Size(m)
}
func (m *DeleteStorehouseItemsByComponentIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorehouseItemsByComponentIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorehouseItemsByComponentIdsRequest proto.InternalMessageInfo

func (m *DeleteStorehouseItemsByComponentIdsRequest) GetStorehouseId() int32 {
	if m != nil {
		return m.StorehouseId
	}
	return 0
}

func (m *DeleteStorehouseItemsByComponentIdsRequest) GetComponentIds() []int32 {
	if m != nil {
		return m.ComponentIds
	}
	return nil
}

type DeleteStorehouseItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorehouseItemResponse) Reset()         { *m = DeleteStorehouseItemResponse{} }
func (m *DeleteStorehouseItemResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStorehouseItemResponse) ProtoMessage()    {}
func (*DeleteStorehouseItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{22}
}

func (m *DeleteStorehouseItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorehouseItemResponse.Unmarshal(m, b)
}
func (m *DeleteStorehouseItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorehouseItemResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStorehouseItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorehouseItemResponse.Merge(m, src)
}
func (m *DeleteStorehouseItemResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStorehouseItemResponse.Size(m)
}
func (m *DeleteStorehouseItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorehouseItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorehouseItemResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Storehouse)(nil), "api.Storehouse")
	proto.RegisterType((*StorehouseItem)(nil), "api.StorehouseItem")
	proto.RegisterType((*CreateStorehouseRequest)(nil), "api.CreateStorehouseRequest")
	proto.RegisterType((*CreateStorehouseResponse)(nil), "api.CreateStorehouseResponse")
	proto.RegisterType((*GetStorehousesListByCityIdRequest)(nil), "api.GetStorehousesListByCityIdRequest")
	proto.RegisterType((*GetStorehouseItemsByStorehouseIdRequest)(nil), "api.GetStorehouseItemsByStorehouseIdRequest")
	proto.RegisterType((*GetStorehousesListResponse)(nil), "api.GetStorehousesListResponse")
	proto.RegisterType((*GetStorehouseItemByIdRequest)(nil), "api.GetStorehouseItemByIdRequest")
	proto.RegisterType((*GetStorehouseItemByIdResponse)(nil), "api.GetStorehouseItemByIdResponse")
	proto.RegisterType((*GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest)(nil), "api.GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest")
	proto.RegisterType((*GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse)(nil), "api.GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse")
	proto.RegisterType((*GetStorehouseItemsByStorehouseIdResponse)(nil), "api.GetStorehouseItemsByStorehouseIdResponse")
	proto.RegisterType((*CreateStorehouseItemForStorehoseRequest)(nil), "api.CreateStorehouseItemForStorehoseRequest")
	proto.RegisterType((*CreateStorehouseItemResponse)(nil), "api.CreateStorehouseItemResponse")
	proto.RegisterType((*UpdateStorehouseItemRequest)(nil), "api.UpdateStorehouseItemRequest")
	proto.RegisterType((*UpdateStorehouseItemResponse)(nil), "api.UpdateStorehouseItemResponse")
	proto.RegisterType((*DeleteStorehouseRequest)(nil), "api.DeleteStorehouseRequest")
	proto.RegisterType((*DeleteStorehouseResponse)(nil), "api.DeleteStorehouseResponse")
	proto.RegisterType((*DeleteStorehousesByCityIdRequest)(nil), "api.DeleteStorehousesByCityIdRequest")
	proto.RegisterType((*DeleteStorehousesByCityIdResponse)(nil), "api.DeleteStorehousesByCityIdResponse")
	proto.RegisterType((*DeleteStorehouseItemRequest)(nil), "api.DeleteStorehouseItemRequest")
	proto.RegisterType((*DeleteStorehouseItemsByComponentIdsRequest)(nil), "api.DeleteStorehouseItemsByComponentIdsRequest")
	proto.RegisterType((*DeleteStorehouseItemResponse)(nil), "api.DeleteStorehouseItemResponse")
}

func init() { proto.RegisterFile("storehouse.proto", fileDescriptor_00c6b29dd839b5b0) }

var fileDescriptor_00c6b29dd839b5b0 = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x51, 0x6f, 0x93, 0x50,
	0x14, 0x2e, 0xb0, 0x76, 0xee, 0x6c, 0xce, 0x7a, 0x9d, 0x29, 0x63, 0x9d, 0xc2, 0x6d, 0x5c, 0xab,
	0x6e, 0xd5, 0xcc, 0x07, 0x7d, 0xd8, 0x1e, 0x6c, 0x75, 0x86, 0xb8, 0x98, 0xac, 0x8b, 0xf1, 0xc9,
	0x68, 0x2d, 0x37, 0x93, 0xa4, 0x05, 0xe4, 0xd2, 0x25, 0x8d, 0x89, 0x89, 0xf1, 0xc1, 0xdf, 0xe3,
	0x0f, 0xf2, 0xbf, 0x2c, 0x50, 0x0a, 0xf4, 0x72, 0x81, 0xb6, 0x6f, 0x2b, 0xe7, 0x3b, 0xdf, 0xf9,
	0xce, 0xe1, 0x9c, 0x8f, 0x41, 0x95, 0x7a, 0xb6, 0x4b, 0xbe, 0xdb, 0x63, 0x4a, 0xda, 0x8e, 0x6b,
	0x7b, 0x36, 0x92, 0xfa, 0x8e, 0x89, 0x75, 0x80, 0xcb, 0x28, 0x80, 0xb6, 0x41, 0x34, 0x0d, 0x59,
	0x50, 0x85, 0x56, 0xb9, 0x27, 0x9a, 0x06, 0x42, 0xb0, 0x66, 0xf5, 0x47, 0x44, 0x16, 0x55, 0xa1,
	0xb5, 0xd1, 0x0b, 0xfe, 0x46, 0x35, 0x58, 0x1f, 0x98, 0xde, 0xe4, 0x8b, 0x69, 0xc8, 0x52, 0x00,
	0xac, 0xf8, 0x3f, 0x75, 0x03, 0xff, 0x82, 0xed, 0x98, 0x4a, 0xf7, 0xc8, 0x28, 0x45, 0xd7, 0x80,
	0xdb, 0xb1, 0x0a, 0x9f, 0x40, 0x0c, 0x42, 0x5b, 0xf1, 0x43, 0xdd, 0x40, 0x1a, 0x6c, 0x0d, 0xec,
	0x91, 0x63, 0x5b, 0xc4, 0xf2, 0xe2, 0x22, 0x9b, 0xd1, 0x33, 0xdd, 0x40, 0x3b, 0x50, 0x1e, 0xd8,
	0x63, 0xcb, 0x93, 0xd7, 0x82, 0xd8, 0xf4, 0x07, 0x3e, 0x83, 0x5a, 0xd7, 0x25, 0x7d, 0x8f, 0xc4,
	0x2a, 0x7a, 0xe4, 0xc7, 0x98, 0x50, 0x2f, 0xea, 0x43, 0xe0, 0xf7, 0x21, 0xce, 0xf5, 0xd1, 0x05,
	0x39, 0xcd, 0x43, 0x1d, 0xdb, 0xa2, 0x04, 0x35, 0xa1, 0xe2, 0x12, 0x3a, 0x1e, 0x7a, 0x01, 0xd5,
	0xe6, 0xf1, 0x9d, 0x76, 0xdf, 0x31, 0xdb, 0x09, 0x60, 0x18, 0xc6, 0x27, 0xa0, 0xbd, 0x23, 0x5e,
	0x1c, 0xa0, 0xe7, 0x26, 0xf5, 0x3a, 0x93, 0x6e, 0x50, 0x62, 0x26, 0x2b, 0x21, 0x41, 0x98, 0x93,
	0xf0, 0x01, 0x9a, 0x73, 0xd9, 0xfe, 0x34, 0x69, 0x67, 0x92, 0x78, 0x10, 0x71, 0xa4, 0x66, 0x2a,
	0xa4, 0x67, 0x8a, 0xdf, 0x82, 0x92, 0x56, 0xc3, 0x6d, 0x4a, 0xca, 0x6b, 0xaa, 0x0d, 0xf5, 0x94,
	0xac, 0x4e, 0xa2, 0x1f, 0xe6, 0x7d, 0xe3, 0x73, 0xd8, 0xcf, 0xc0, 0x87, 0x95, 0x9f, 0x32, 0xe3,
	0xbc, 0xc7, 0x54, 0xf6, 0x13, 0xa2, 0xea, 0x7f, 0x04, 0x78, 0x59, 0x34, 0x95, 0xd7, 0x96, 0xd1,
	0x9d, 0x2d, 0x0a, 0xd5, 0x0d, 0xba, 0xcc, 0x94, 0x7c, 0x50, 0x72, 0xf3, 0xa8, 0x2c, 0xaa, 0x92,
	0x0f, 0x4a, 0xac, 0x1e, 0xc5, 0x57, 0xf0, 0x6a, 0x79, 0x11, 0x9c, 0x76, 0xa5, 0xa2, 0x76, 0x3f,
	0x41, 0xab, 0x78, 0x07, 0x56, 0x21, 0xfe, 0x2b, 0x40, 0x93, 0x5d, 0x70, 0x1f, 0x70, 0x66, 0xbb,
	0xe1, 0x83, 0xf8, 0x70, 0xd8, 0x63, 0x14, 0xd2, 0xc7, 0xb8, 0xd0, 0x51, 0x47, 0x17, 0x2b, 0x25,
	0x2f, 0xf6, 0x3d, 0xd4, 0x79, 0x42, 0x56, 0x5b, 0x8f, 0x2e, 0xec, 0x7d, 0x74, 0x0c, 0x0e, 0x19,
	0x77, 0x37, 0x63, 0x45, 0x22, 0xa3, 0x88, 0x4f, 0xb2, 0x8a, 0xa2, 0xc7, 0x50, 0x7b, 0x43, 0x86,
	0x84, 0x67, 0x48, 0xec, 0xa5, 0x28, 0x20, 0xa7, 0xa1, 0xd3, 0x9a, 0xf8, 0x14, 0x54, 0x36, 0x46,
	0x59, 0x27, 0xd9, 0x85, 0x5b, 0xa1, 0x93, 0xd0, 0x60, 0x05, 0xca, 0xbd, 0xf5, 0xa9, 0x95, 0x50,
	0xdc, 0x00, 0x2d, 0x27, 0x3d, 0xac, 0x71, 0x04, 0x7b, 0x2c, 0x28, 0x67, 0x78, 0x78, 0x0c, 0x4f,
	0x78, 0x70, 0x9f, 0x37, 0x71, 0x2b, 0x4b, 0x1d, 0x1f, 0x86, 0xb9, 0x3b, 0xe3, 0xde, 0xde, 0x03,
	0xa8, 0xf3, 0x55, 0x4e, 0xbb, 0x38, 0xfe, 0xbf, 0x01, 0x77, 0xe3, 0xd0, 0x25, 0x71, 0xaf, 0xcd,
	0x01, 0x41, 0x17, 0x50, 0x65, 0xb7, 0x0c, 0xd5, 0x83, 0xf7, 0x96, 0xf1, 0xb9, 0x50, 0xf6, 0x33,
	0xa2, 0xe1, 0xb0, 0x4a, 0xe8, 0x8a, 0xe7, 0xa7, 0xb3, 0xa1, 0xa2, 0x83, 0x20, 0xbd, 0xd0, 0xfe,
	0x95, 0x87, 0x19, 0xb8, 0x44, 0xa1, 0xaf, 0x70, 0x9f, 0xeb, 0xa0, 0x48, 0x4b, 0xe7, 0x32, 0x6e,
	0xac, 0xe0, 0x3c, 0x48, 0x54, 0xe1, 0xb7, 0x00, 0x6a, 0x91, 0xcf, 0xa0, 0x43, 0x3e, 0x15, 0xff,
	0x93, 0xa4, 0x1c, 0x2d, 0x88, 0x8e, 0x34, 0xfc, 0x13, 0xe0, 0xf9, 0xb2, 0xa6, 0x8a, 0x4e, 0x16,
	0xaa, 0x92, 0xf1, 0x41, 0x50, 0x4e, 0x57, 0xcc, 0x8e, 0x34, 0x5f, 0x83, 0x96, 0x6f, 0xa2, 0xfe,
	0x9a, 0x1d, 0x72, 0x17, 0x29, 0xc3, 0x6c, 0x15, 0x2d, 0x13, 0x9d, 0xa8, 0xfb, 0x19, 0x76, 0x78,
	0x0e, 0x85, 0xd4, 0x20, 0x39, 0xc7, 0x01, 0x43, 0xfa, 0x3c, 0x7b, 0x9b, 0xd2, 0xf3, 0x4e, 0x2c,
	0xa4, 0xcf, 0xf1, 0x88, 0x90, 0x3e, 0xef, 0x3e, 0x71, 0x09, 0xfd, 0x84, 0xc6, 0x02, 0xc6, 0x81,
	0x9e, 0x65, 0x72, 0xf1, 0x2d, 0x66, 0xb1, 0xe2, 0x17, 0x50, 0x65, 0x11, 0xa1, 0x11, 0x64, 0xd8,
	0x74, 0x68, 0x04, 0x99, 0xce, 0x5c, 0x42, 0x43, 0xd8, 0xcd, 0x34, 0x57, 0xf4, 0x88, 0x9b, 0xcd,
	0x7a, 0xb7, 0x72, 0x50, 0x04, 0x9b, 0x55, 0xfb, 0x56, 0x09, 0xfe, 0x71, 0x7f, 0x71, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x2f, 0xdb, 0x2a, 0x73, 0xcc, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorehouseServiceClient is the client API for StorehouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorehouseServiceClient interface {
	CreateStorehouse(ctx context.Context, in *CreateStorehouseRequest, opts ...grpc.CallOption) (*CreateStorehouseResponse, error)
	GetStorehousesListByCityId(ctx context.Context, in *GetStorehousesListByCityIdRequest, opts ...grpc.CallOption) (*GetStorehousesListResponse, error)
	GetStorehouseItemById(ctx context.Context, in *GetStorehouseItemByIdRequest, opts ...grpc.CallOption) (*GetStorehouseItemByIdResponse, error)
	GetStorehouseItemsByStorehouseId(ctx context.Context, in *GetStorehouseItemsByStorehouseIdRequest, opts ...grpc.CallOption) (*GetStorehouseItemsByStorehouseIdResponse, error)
	GetStorehouseItemsByStorehouseIdAndComponentsIds(ctx context.Context, in *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest, opts ...grpc.CallOption) (*GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse, error)
	CreateStorehouseItemForStorehouse(ctx context.Context, in *CreateStorehouseItemForStorehoseRequest, opts ...grpc.CallOption) (*CreateStorehouseItemResponse, error)
	UpdateStorehouseItem(ctx context.Context, in *UpdateStorehouseItemRequest, opts ...grpc.CallOption) (*UpdateStorehouseItemResponse, error)
	DeleteStorehouseItem(ctx context.Context, in *DeleteStorehouseItemRequest, opts ...grpc.CallOption) (*DeleteStorehouseItemResponse, error)
	DeleteStorehouseItemsByComponentIds(ctx context.Context, in *DeleteStorehouseItemsByComponentIdsRequest, opts ...grpc.CallOption) (*DeleteStorehouseItemResponse, error)
	DeleteStorehouse(ctx context.Context, in *DeleteStorehouseRequest, opts ...grpc.CallOption) (*DeleteStorehouseResponse, error)
	DeleteStorehousesByCityId(ctx context.Context, in *DeleteStorehousesByCityIdRequest, opts ...grpc.CallOption) (*DeleteStorehousesByCityIdResponse, error)
}

type storehouseServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorehouseServiceClient(cc *grpc.ClientConn) StorehouseServiceClient {
	return &storehouseServiceClient{cc}
}

func (c *storehouseServiceClient) CreateStorehouse(ctx context.Context, in *CreateStorehouseRequest, opts ...grpc.CallOption) (*CreateStorehouseResponse, error) {
	out := new(CreateStorehouseResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/CreateStorehouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) GetStorehousesListByCityId(ctx context.Context, in *GetStorehousesListByCityIdRequest, opts ...grpc.CallOption) (*GetStorehousesListResponse, error) {
	out := new(GetStorehousesListResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/GetStorehousesListByCityId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) GetStorehouseItemById(ctx context.Context, in *GetStorehouseItemByIdRequest, opts ...grpc.CallOption) (*GetStorehouseItemByIdResponse, error) {
	out := new(GetStorehouseItemByIdResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/GetStorehouseItemById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) GetStorehouseItemsByStorehouseId(ctx context.Context, in *GetStorehouseItemsByStorehouseIdRequest, opts ...grpc.CallOption) (*GetStorehouseItemsByStorehouseIdResponse, error) {
	out := new(GetStorehouseItemsByStorehouseIdResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/GetStorehouseItemsByStorehouseId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) GetStorehouseItemsByStorehouseIdAndComponentsIds(ctx context.Context, in *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest, opts ...grpc.CallOption) (*GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse, error) {
	out := new(GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/GetStorehouseItemsByStorehouseIdAndComponentsIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) CreateStorehouseItemForStorehouse(ctx context.Context, in *CreateStorehouseItemForStorehoseRequest, opts ...grpc.CallOption) (*CreateStorehouseItemResponse, error) {
	out := new(CreateStorehouseItemResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/CreateStorehouseItemForStorehouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) UpdateStorehouseItem(ctx context.Context, in *UpdateStorehouseItemRequest, opts ...grpc.CallOption) (*UpdateStorehouseItemResponse, error) {
	out := new(UpdateStorehouseItemResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/UpdateStorehouseItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) DeleteStorehouseItem(ctx context.Context, in *DeleteStorehouseItemRequest, opts ...grpc.CallOption) (*DeleteStorehouseItemResponse, error) {
	out := new(DeleteStorehouseItemResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/DeleteStorehouseItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) DeleteStorehouseItemsByComponentIds(ctx context.Context, in *DeleteStorehouseItemsByComponentIdsRequest, opts ...grpc.CallOption) (*DeleteStorehouseItemResponse, error) {
	out := new(DeleteStorehouseItemResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/DeleteStorehouseItemsByComponentIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) DeleteStorehouse(ctx context.Context, in *DeleteStorehouseRequest, opts ...grpc.CallOption) (*DeleteStorehouseResponse, error) {
	out := new(DeleteStorehouseResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/DeleteStorehouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) DeleteStorehousesByCityId(ctx context.Context, in *DeleteStorehousesByCityIdRequest, opts ...grpc.CallOption) (*DeleteStorehousesByCityIdResponse, error) {
	out := new(DeleteStorehousesByCityIdResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/DeleteStorehousesByCityId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorehouseServiceServer is the server API for StorehouseService service.
type StorehouseServiceServer interface {
	CreateStorehouse(context.Context, *CreateStorehouseRequest) (*CreateStorehouseResponse, error)
	GetStorehousesListByCityId(context.Context, *GetStorehousesListByCityIdRequest) (*GetStorehousesListResponse, error)
	GetStorehouseItemById(context.Context, *GetStorehouseItemByIdRequest) (*GetStorehouseItemByIdResponse, error)
	GetStorehouseItemsByStorehouseId(context.Context, *GetStorehouseItemsByStorehouseIdRequest) (*GetStorehouseItemsByStorehouseIdResponse, error)
	GetStorehouseItemsByStorehouseIdAndComponentsIds(context.Context, *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) (*GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse, error)
	CreateStorehouseItemForStorehouse(context.Context, *CreateStorehouseItemForStorehoseRequest) (*CreateStorehouseItemResponse, error)
	UpdateStorehouseItem(context.Context, *UpdateStorehouseItemRequest) (*UpdateStorehouseItemResponse, error)
	DeleteStorehouseItem(context.Context, *DeleteStorehouseItemRequest) (*DeleteStorehouseItemResponse, error)
	DeleteStorehouseItemsByComponentIds(context.Context, *DeleteStorehouseItemsByComponentIdsRequest) (*DeleteStorehouseItemResponse, error)
	DeleteStorehouse(context.Context, *DeleteStorehouseRequest) (*DeleteStorehouseResponse, error)
	DeleteStorehousesByCityId(context.Context, *DeleteStorehousesByCityIdRequest) (*DeleteStorehousesByCityIdResponse, error)
}

// UnimplementedStorehouseServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStorehouseServiceServer struct {
}

func (*UnimplementedStorehouseServiceServer) CreateStorehouse(ctx context.Context, req *CreateStorehouseRequest) (*CreateStorehouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStorehouse not implemented")
}
func (*UnimplementedStorehouseServiceServer) GetStorehousesListByCityId(ctx context.Context, req *GetStorehousesListByCityIdRequest) (*GetStorehousesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorehousesListByCityId not implemented")
}
func (*UnimplementedStorehouseServiceServer) GetStorehouseItemById(ctx context.Context, req *GetStorehouseItemByIdRequest) (*GetStorehouseItemByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorehouseItemById not implemented")
}
func (*UnimplementedStorehouseServiceServer) GetStorehouseItemsByStorehouseId(ctx context.Context, req *GetStorehouseItemsByStorehouseIdRequest) (*GetStorehouseItemsByStorehouseIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorehouseItemsByStorehouseId not implemented")
}
func (*UnimplementedStorehouseServiceServer) GetStorehouseItemsByStorehouseIdAndComponentsIds(ctx context.Context, req *GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest) (*GetStorehouseItemsByStorehouseIdAndComponentsIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorehouseItemsByStorehouseIdAndComponentsIds not implemented")
}
func (*UnimplementedStorehouseServiceServer) CreateStorehouseItemForStorehouse(ctx context.Context, req *CreateStorehouseItemForStorehoseRequest) (*CreateStorehouseItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStorehouseItemForStorehouse not implemented")
}
func (*UnimplementedStorehouseServiceServer) UpdateStorehouseItem(ctx context.Context, req *UpdateStorehouseItemRequest) (*UpdateStorehouseItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStorehouseItem not implemented")
}
func (*UnimplementedStorehouseServiceServer) DeleteStorehouseItem(ctx context.Context, req *DeleteStorehouseItemRequest) (*DeleteStorehouseItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStorehouseItem not implemented")
}
func (*UnimplementedStorehouseServiceServer) DeleteStorehouseItemsByComponentIds(ctx context.Context, req *DeleteStorehouseItemsByComponentIdsRequest) (*DeleteStorehouseItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStorehouseItemsByComponentIds not implemented")
}
func (*UnimplementedStorehouseServiceServer) DeleteStorehouse(ctx context.Context, req *DeleteStorehouseRequest) (*DeleteStorehouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStorehouse not implemented")
}
func (*UnimplementedStorehouseServiceServer) DeleteStorehousesByCityId(ctx context.Context, req *DeleteStorehousesByCityIdRequest) (*DeleteStorehousesByCityIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStorehousesByCityId not implemented")
}

func RegisterStorehouseServiceServer(s *grpc.Server, srv StorehouseServiceServer) {
	s.RegisterService(&_StorehouseService_serviceDesc, srv)
}

func _StorehouseService_CreateStorehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStorehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).CreateStorehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/CreateStorehouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).CreateStorehouse(ctx, req.(*CreateStorehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_GetStorehousesListByCityId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorehousesListByCityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).GetStorehousesListByCityId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/GetStorehousesListByCityId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).GetStorehousesListByCityId(ctx, req.(*GetStorehousesListByCityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_GetStorehouseItemById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorehouseItemByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).GetStorehouseItemById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/GetStorehouseItemById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).GetStorehouseItemById(ctx, req.(*GetStorehouseItemByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_GetStorehouseItemsByStorehouseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorehouseItemsByStorehouseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).GetStorehouseItemsByStorehouseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/GetStorehouseItemsByStorehouseId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).GetStorehouseItemsByStorehouseId(ctx, req.(*GetStorehouseItemsByStorehouseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_GetStorehouseItemsByStorehouseIdAndComponentsIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).GetStorehouseItemsByStorehouseIdAndComponentsIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/GetStorehouseItemsByStorehouseIdAndComponentsIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).GetStorehouseItemsByStorehouseIdAndComponentsIds(ctx, req.(*GetStorehouseItemsByStorehouseIdAndComponentsIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_CreateStorehouseItemForStorehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStorehouseItemForStorehoseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).CreateStorehouseItemForStorehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/CreateStorehouseItemForStorehouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).CreateStorehouseItemForStorehouse(ctx, req.(*CreateStorehouseItemForStorehoseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_UpdateStorehouseItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStorehouseItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).UpdateStorehouseItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/UpdateStorehouseItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).UpdateStorehouseItem(ctx, req.(*UpdateStorehouseItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_DeleteStorehouseItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStorehouseItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).DeleteStorehouseItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/DeleteStorehouseItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).DeleteStorehouseItem(ctx, req.(*DeleteStorehouseItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_DeleteStorehouseItemsByComponentIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStorehouseItemsByComponentIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).DeleteStorehouseItemsByComponentIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/DeleteStorehouseItemsByComponentIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).DeleteStorehouseItemsByComponentIds(ctx, req.(*DeleteStorehouseItemsByComponentIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_DeleteStorehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStorehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).DeleteStorehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/DeleteStorehouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).DeleteStorehouse(ctx, req.(*DeleteStorehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_DeleteStorehousesByCityId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStorehousesByCityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).DeleteStorehousesByCityId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/DeleteStorehousesByCityId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).DeleteStorehousesByCityId(ctx, req.(*DeleteStorehousesByCityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorehouseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.StorehouseService",
	HandlerType: (*StorehouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStorehouse",
			Handler:    _StorehouseService_CreateStorehouse_Handler,
		},
		{
			MethodName: "GetStorehousesListByCityId",
			Handler:    _StorehouseService_GetStorehousesListByCityId_Handler,
		},
		{
			MethodName: "GetStorehouseItemById",
			Handler:    _StorehouseService_GetStorehouseItemById_Handler,
		},
		{
			MethodName: "GetStorehouseItemsByStorehouseId",
			Handler:    _StorehouseService_GetStorehouseItemsByStorehouseId_Handler,
		},
		{
			MethodName: "GetStorehouseItemsByStorehouseIdAndComponentsIds",
			Handler:    _StorehouseService_GetStorehouseItemsByStorehouseIdAndComponentsIds_Handler,
		},
		{
			MethodName: "CreateStorehouseItemForStorehouse",
			Handler:    _StorehouseService_CreateStorehouseItemForStorehouse_Handler,
		},
		{
			MethodName: "UpdateStorehouseItem",
			Handler:    _StorehouseService_UpdateStorehouseItem_Handler,
		},
		{
			MethodName: "DeleteStorehouseItem",
			Handler:    _StorehouseService_DeleteStorehouseItem_Handler,
		},
		{
			MethodName: "DeleteStorehouseItemsByComponentIds",
			Handler:    _StorehouseService_DeleteStorehouseItemsByComponentIds_Handler,
		},
		{
			MethodName: "DeleteStorehouse",
			Handler:    _StorehouseService_DeleteStorehouse_Handler,
		},
		{
			MethodName: "DeleteStorehousesByCityId",
			Handler:    _StorehouseService_DeleteStorehousesByCityId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storehouse.proto",
}
