// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storehouse.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateStorehouseRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CityId               int32    `protobuf:"varint,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStorehouseRequest) Reset()         { *m = CreateStorehouseRequest{} }
func (m *CreateStorehouseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStorehouseRequest) ProtoMessage()    {}
func (*CreateStorehouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{0}
}

func (m *CreateStorehouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStorehouseRequest.Unmarshal(m, b)
}
func (m *CreateStorehouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStorehouseRequest.Marshal(b, m, deterministic)
}
func (m *CreateStorehouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStorehouseRequest.Merge(m, src)
}
func (m *CreateStorehouseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStorehouseRequest.Size(m)
}
func (m *CreateStorehouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStorehouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStorehouseRequest proto.InternalMessageInfo

func (m *CreateStorehouseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateStorehouseRequest) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type Storehouse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CityId               int32    `protobuf:"varint,3,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Storehouse) Reset()         { *m = Storehouse{} }
func (m *Storehouse) String() string { return proto.CompactTextString(m) }
func (*Storehouse) ProtoMessage()    {}
func (*Storehouse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{1}
}

func (m *Storehouse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storehouse.Unmarshal(m, b)
}
func (m *Storehouse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storehouse.Marshal(b, m, deterministic)
}
func (m *Storehouse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storehouse.Merge(m, src)
}
func (m *Storehouse) XXX_Size() int {
	return xxx_messageInfo_Storehouse.Size(m)
}
func (m *Storehouse) XXX_DiscardUnknown() {
	xxx_messageInfo_Storehouse.DiscardUnknown(m)
}

var xxx_messageInfo_Storehouse proto.InternalMessageInfo

func (m *Storehouse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Storehouse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Storehouse) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type GetStorehousesListByCityIdRequest struct {
	CityId               int32    `protobuf:"varint,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStorehousesListByCityIdRequest) Reset()         { *m = GetStorehousesListByCityIdRequest{} }
func (m *GetStorehousesListByCityIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetStorehousesListByCityIdRequest) ProtoMessage()    {}
func (*GetStorehousesListByCityIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{2}
}

func (m *GetStorehousesListByCityIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehousesListByCityIdRequest.Unmarshal(m, b)
}
func (m *GetStorehousesListByCityIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehousesListByCityIdRequest.Marshal(b, m, deterministic)
}
func (m *GetStorehousesListByCityIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehousesListByCityIdRequest.Merge(m, src)
}
func (m *GetStorehousesListByCityIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetStorehousesListByCityIdRequest.Size(m)
}
func (m *GetStorehousesListByCityIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehousesListByCityIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehousesListByCityIdRequest proto.InternalMessageInfo

func (m *GetStorehousesListByCityIdRequest) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type GetStorehousesListResponse struct {
	Items                []*Storehouse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetStorehousesListResponse) Reset()         { *m = GetStorehousesListResponse{} }
func (m *GetStorehousesListResponse) String() string { return proto.CompactTextString(m) }
func (*GetStorehousesListResponse) ProtoMessage()    {}
func (*GetStorehousesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{3}
}

func (m *GetStorehousesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStorehousesListResponse.Unmarshal(m, b)
}
func (m *GetStorehousesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStorehousesListResponse.Marshal(b, m, deterministic)
}
func (m *GetStorehousesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStorehousesListResponse.Merge(m, src)
}
func (m *GetStorehousesListResponse) XXX_Size() int {
	return xxx_messageInfo_GetStorehousesListResponse.Size(m)
}
func (m *GetStorehousesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStorehousesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStorehousesListResponse proto.InternalMessageInfo

func (m *GetStorehousesListResponse) GetItems() []*Storehouse {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StorehouseId         int32    `protobuf:"varint,2,opt,name=storehouse_id,json=storehouseId,proto3" json:"storehouse_id,omitempty"`
	DetailId             int32    `protobuf:"varint,3,opt,name=detail_id,json=detailId,proto3" json:"detail_id,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{4}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetStorehouseId() int32 {
	if m != nil {
		return m.StorehouseId
	}
	return 0
}

func (m *Item) GetDetailId() int32 {
	if m != nil {
		return m.DetailId
	}
	return 0
}

func (m *Item) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetItemsByStorehouseIdRequest struct {
	StorehouseId         int32    `protobuf:"varint,1,opt,name=storehouse_id,json=storehouseId,proto3" json:"storehouse_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemsByStorehouseIdRequest) Reset()         { *m = GetItemsByStorehouseIdRequest{} }
func (m *GetItemsByStorehouseIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetItemsByStorehouseIdRequest) ProtoMessage()    {}
func (*GetItemsByStorehouseIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{5}
}

func (m *GetItemsByStorehouseIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemsByStorehouseIdRequest.Unmarshal(m, b)
}
func (m *GetItemsByStorehouseIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemsByStorehouseIdRequest.Marshal(b, m, deterministic)
}
func (m *GetItemsByStorehouseIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemsByStorehouseIdRequest.Merge(m, src)
}
func (m *GetItemsByStorehouseIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetItemsByStorehouseIdRequest.Size(m)
}
func (m *GetItemsByStorehouseIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemsByStorehouseIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemsByStorehouseIdRequest proto.InternalMessageInfo

func (m *GetItemsByStorehouseIdRequest) GetStorehouseId() int32 {
	if m != nil {
		return m.StorehouseId
	}
	return 0
}

type GetItemsByStorehouseIdResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemsByStorehouseIdResponse) Reset()         { *m = GetItemsByStorehouseIdResponse{} }
func (m *GetItemsByStorehouseIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetItemsByStorehouseIdResponse) ProtoMessage()    {}
func (*GetItemsByStorehouseIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{6}
}

func (m *GetItemsByStorehouseIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemsByStorehouseIdResponse.Unmarshal(m, b)
}
func (m *GetItemsByStorehouseIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemsByStorehouseIdResponse.Marshal(b, m, deterministic)
}
func (m *GetItemsByStorehouseIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemsByStorehouseIdResponse.Merge(m, src)
}
func (m *GetItemsByStorehouseIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetItemsByStorehouseIdResponse.Size(m)
}
func (m *GetItemsByStorehouseIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemsByStorehouseIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemsByStorehouseIdResponse proto.InternalMessageInfo

func (m *GetItemsByStorehouseIdResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateItemForStorehoseRequest struct {
	DetailId             int32    `protobuf:"varint,1,opt,name=detail_id,json=detailId,proto3" json:"detail_id,omitempty"`
	StorehouseId         int32    `protobuf:"varint,2,opt,name=storehouse_id,json=storehouseId,proto3" json:"storehouse_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemForStorehoseRequest) Reset()         { *m = CreateItemForStorehoseRequest{} }
func (m *CreateItemForStorehoseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateItemForStorehoseRequest) ProtoMessage()    {}
func (*CreateItemForStorehoseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{7}
}

func (m *CreateItemForStorehoseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemForStorehoseRequest.Unmarshal(m, b)
}
func (m *CreateItemForStorehoseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemForStorehoseRequest.Marshal(b, m, deterministic)
}
func (m *CreateItemForStorehoseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemForStorehoseRequest.Merge(m, src)
}
func (m *CreateItemForStorehoseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateItemForStorehoseRequest.Size(m)
}
func (m *CreateItemForStorehoseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemForStorehoseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemForStorehoseRequest proto.InternalMessageInfo

func (m *CreateItemForStorehoseRequest) GetDetailId() int32 {
	if m != nil {
		return m.DetailId
	}
	return 0
}

func (m *CreateItemForStorehoseRequest) GetStorehouseId() int32 {
	if m != nil {
		return m.StorehouseId
	}
	return 0
}

type UpdateItemRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemRequest) Reset()         { *m = UpdateItemRequest{} }
func (m *UpdateItemRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateItemRequest) ProtoMessage()    {}
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{8}
}

func (m *UpdateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemRequest.Unmarshal(m, b)
}
func (m *UpdateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemRequest.Marshal(b, m, deterministic)
}
func (m *UpdateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemRequest.Merge(m, src)
}
func (m *UpdateItemRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateItemRequest.Size(m)
}
func (m *UpdateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemRequest proto.InternalMessageInfo

func (m *UpdateItemRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateItemRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DeleteStorehouseRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorehouseRequest) Reset()         { *m = DeleteStorehouseRequest{} }
func (m *DeleteStorehouseRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStorehouseRequest) ProtoMessage()    {}
func (*DeleteStorehouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{9}
}

func (m *DeleteStorehouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorehouseRequest.Unmarshal(m, b)
}
func (m *DeleteStorehouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorehouseRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStorehouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorehouseRequest.Merge(m, src)
}
func (m *DeleteStorehouseRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStorehouseRequest.Size(m)
}
func (m *DeleteStorehouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorehouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorehouseRequest proto.InternalMessageInfo

func (m *DeleteStorehouseRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteItemRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemRequest) Reset()         { *m = DeleteItemRequest{} }
func (m *DeleteItemRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteItemRequest) ProtoMessage()    {}
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{10}
}

func (m *DeleteItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemRequest.Unmarshal(m, b)
}
func (m *DeleteItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemRequest.Marshal(b, m, deterministic)
}
func (m *DeleteItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemRequest.Merge(m, src)
}
func (m *DeleteItemRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteItemRequest.Size(m)
}
func (m *DeleteItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemRequest proto.InternalMessageInfo

func (m *DeleteItemRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00c6b29dd839b5b0, []int{11}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateStorehouseRequest)(nil), "api.CreateStorehouseRequest")
	proto.RegisterType((*Storehouse)(nil), "api.Storehouse")
	proto.RegisterType((*GetStorehousesListByCityIdRequest)(nil), "api.GetStorehousesListByCityIdRequest")
	proto.RegisterType((*GetStorehousesListResponse)(nil), "api.GetStorehousesListResponse")
	proto.RegisterType((*Item)(nil), "api.Item")
	proto.RegisterType((*GetItemsByStorehouseIdRequest)(nil), "api.GetItemsByStorehouseIdRequest")
	proto.RegisterType((*GetItemsByStorehouseIdResponse)(nil), "api.GetItemsByStorehouseIdResponse")
	proto.RegisterType((*CreateItemForStorehoseRequest)(nil), "api.CreateItemForStorehoseRequest")
	proto.RegisterType((*UpdateItemRequest)(nil), "api.UpdateItemRequest")
	proto.RegisterType((*DeleteStorehouseRequest)(nil), "api.DeleteStorehouseRequest")
	proto.RegisterType((*DeleteItemRequest)(nil), "api.DeleteItemRequest")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

func init() { proto.RegisterFile("storehouse.proto", fileDescriptor_00c6b29dd839b5b0) }

var fileDescriptor_00c6b29dd839b5b0 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0xa5, 0x85, 0xee, 0xca, 0xf5, 0x0b, 0x6e, 0xcc, 0x42, 0xaa, 0xeb, 0xe2, 0x10, 0x0d, 0xbe,
	0x90, 0x88, 0x4f, 0x26, 0xc6, 0xc4, 0x65, 0xdd, 0x4d, 0x8d, 0x4f, 0x25, 0x3e, 0x9b, 0xca, 0xdc,
	0xe8, 0x24, 0x0b, 0xad, 0x9d, 0xc1, 0x84, 0x9f, 0xe2, 0xbf, 0x35, 0x9d, 0x76, 0x98, 0x7e, 0xd0,
	0xd5, 0x37, 0x7a, 0xef, 0x9c, 0x73, 0x39, 0xe7, 0x9e, 0x19, 0x18, 0x48, 0x15, 0xa7, 0xf4, 0x33,
	0xde, 0x49, 0x9a, 0x27, 0x69, 0xac, 0x62, 0xec, 0x46, 0x89, 0x60, 0xd7, 0x30, 0x5a, 0xa6, 0x14,
	0x29, 0x5a, 0x1d, 0xda, 0x21, 0xfd, 0xda, 0x91, 0x54, 0x88, 0xd0, 0xdb, 0x46, 0x1b, 0x1a, 0x3b,
	0x13, 0x67, 0xd6, 0x0f, 0xf5, 0x6f, 0x1c, 0xc1, 0xe9, 0x5a, 0xa8, 0xfd, 0x37, 0xc1, 0xc7, 0xee,
	0xc4, 0x99, 0x79, 0xe1, 0x49, 0xf6, 0x19, 0x70, 0x16, 0x00, 0x58, 0x06, 0x7c, 0x04, 0xae, 0xe0,
	0x1a, 0xe8, 0x85, 0xae, 0xe0, 0x07, 0x2a, 0xf7, 0x38, 0x55, 0xb7, 0x42, 0xf5, 0x1e, 0x5e, 0xdc,
	0x90, 0xb2, 0x6c, 0xf2, 0x8b, 0x90, 0xea, 0x72, 0xbf, 0xd4, 0x5d, 0xf3, 0xe7, 0x4a, 0x68, 0xa7,
	0x82, 0x5e, 0x82, 0xdf, 0x44, 0x87, 0x24, 0x93, 0x78, 0x2b, 0x09, 0x5f, 0x82, 0x27, 0x14, 0x6d,
	0xe4, 0xd8, 0x99, 0x74, 0x67, 0xf7, 0x17, 0x8f, 0xe7, 0x51, 0x22, 0xe6, 0x25, 0xe9, 0x79, 0x97,
	0x6d, 0xa1, 0x17, 0x28, 0xda, 0x34, 0x74, 0x4c, 0xe1, 0xa1, 0xb5, 0xd1, 0x9a, 0xf0, 0xc0, 0x16,
	0x03, 0x8e, 0x4f, 0xa1, 0xcf, 0x49, 0x45, 0xe2, 0xd6, 0x4a, 0xbb, 0x97, 0x17, 0x02, 0x8e, 0x4f,
	0xc0, 0x5b, 0xc7, 0xbb, 0xad, 0x1a, 0xf7, 0x74, 0x23, 0xff, 0x60, 0x57, 0x70, 0x7e, 0x43, 0x2a,
	0x1b, 0x29, 0x2f, 0xf7, 0xab, 0x12, 0x99, 0x91, 0xdb, 0x18, 0xec, 0x34, 0x07, 0xb3, 0x8f, 0xf0,
	0xbc, 0x8d, 0xa5, 0x90, 0x7f, 0x51, 0x95, 0xdf, 0xd7, 0xf2, 0x33, 0x80, 0x11, 0x1e, 0xc1, 0x79,
	0x1e, 0x87, 0xac, 0x78, 0x1d, 0xa7, 0x05, 0x8b, 0x0d, 0x45, 0x45, 0x9c, 0x53, 0x13, 0xf7, 0x3f,
	0xf6, 0xb0, 0x77, 0x30, 0xfc, 0x9a, 0xf0, 0x62, 0x84, 0xa1, 0xad, 0x1b, 0x7d, 0xb0, 0xc9, 0x2d,
	0xdb, 0xf4, 0x1a, 0x46, 0x57, 0x74, 0x4b, 0xc7, 0xc2, 0x5a, 0x23, 0x60, 0x53, 0x18, 0xe6, 0x47,
	0xef, 0x98, 0xc2, 0x4e, 0xc1, 0xfb, 0xb4, 0x49, 0xd4, 0x7e, 0xf1, 0xa7, 0x07, 0x43, 0xcb, 0xb9,
	0xa2, 0xf4, 0xb7, 0x58, 0x13, 0x2e, 0x61, 0x50, 0xbf, 0x1b, 0xf8, 0x4c, 0x5b, 0xd6, 0x72, 0x65,
	0xfc, 0x7a, 0x9e, 0x58, 0x07, 0x7f, 0x1c, 0xcb, 0xa3, 0x49, 0x33, 0xbe, 0xd2, 0x80, 0x7f, 0xc6,
	0xdd, 0xbf, 0x68, 0x39, 0x67, 0x36, 0xcb, 0x3a, 0xb8, 0x86, 0xb3, 0xe3, 0xdb, 0x47, 0x66, 0xc0,
	0xed, 0x01, 0xf3, 0xa7, 0x77, 0x9e, 0x39, 0x0c, 0xf9, 0x6c, 0x9e, 0x8b, 0x6a, 0x3e, 0x32, 0x67,
	0x58, 0xc9, 0x99, 0x96, 0xf4, 0xf8, 0x36, 0x70, 0xac, 0x83, 0x6f, 0x00, 0x6c, 0x10, 0xf0, 0x4c,
	0xb7, 0x1a, 0xc9, 0xa8, 0x42, 0x16, 0x00, 0x76, 0xab, 0x05, 0xa4, 0xb1, 0x66, 0x1f, 0x74, 0x5d,
	0x6f, 0x96, 0x75, 0xf0, 0x03, 0x0c, 0xea, 0xa1, 0x29, 0xb6, 0xd8, 0x92, 0xa5, 0x2a, 0xfe, 0xfb,
	0x89, 0x7e, 0x2d, 0xdf, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x4d, 0x9d, 0x7a, 0x41, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorehouseServiceClient is the client API for StorehouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorehouseServiceClient interface {
	CreateStorehouse(ctx context.Context, in *CreateStorehouseRequest, opts ...grpc.CallOption) (*Storehouse, error)
	GetStorehousesListByCityId(ctx context.Context, in *GetStorehousesListByCityIdRequest, opts ...grpc.CallOption) (*GetStorehousesListResponse, error)
	GetItemsByStorehouseId(ctx context.Context, in *GetItemsByStorehouseIdRequest, opts ...grpc.CallOption) (*GetItemsByStorehouseIdResponse, error)
	CreateItemForStorehouse(ctx context.Context, in *CreateItemForStorehoseRequest, opts ...grpc.CallOption) (*Item, error)
	UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*Item, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteStorehouse(ctx context.Context, in *DeleteStorehouseRequest, opts ...grpc.CallOption) (*Empty, error)
}

type storehouseServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorehouseServiceClient(cc *grpc.ClientConn) StorehouseServiceClient {
	return &storehouseServiceClient{cc}
}

func (c *storehouseServiceClient) CreateStorehouse(ctx context.Context, in *CreateStorehouseRequest, opts ...grpc.CallOption) (*Storehouse, error) {
	out := new(Storehouse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/CreateStorehouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) GetStorehousesListByCityId(ctx context.Context, in *GetStorehousesListByCityIdRequest, opts ...grpc.CallOption) (*GetStorehousesListResponse, error) {
	out := new(GetStorehousesListResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/GetStorehousesListByCityId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) GetItemsByStorehouseId(ctx context.Context, in *GetItemsByStorehouseIdRequest, opts ...grpc.CallOption) (*GetItemsByStorehouseIdResponse, error) {
	out := new(GetItemsByStorehouseIdResponse)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/GetItemsByStorehouseId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) CreateItemForStorehouse(ctx context.Context, in *CreateItemForStorehoseRequest, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/CreateItemForStorehouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/UpdateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storehouseServiceClient) DeleteStorehouse(ctx context.Context, in *DeleteStorehouseRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.StorehouseService/DeleteStorehouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorehouseServiceServer is the server API for StorehouseService service.
type StorehouseServiceServer interface {
	CreateStorehouse(context.Context, *CreateStorehouseRequest) (*Storehouse, error)
	GetStorehousesListByCityId(context.Context, *GetStorehousesListByCityIdRequest) (*GetStorehousesListResponse, error)
	GetItemsByStorehouseId(context.Context, *GetItemsByStorehouseIdRequest) (*GetItemsByStorehouseIdResponse, error)
	CreateItemForStorehouse(context.Context, *CreateItemForStorehoseRequest) (*Item, error)
	UpdateItem(context.Context, *UpdateItemRequest) (*Item, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*Empty, error)
	DeleteStorehouse(context.Context, *DeleteStorehouseRequest) (*Empty, error)
}

// UnimplementedStorehouseServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStorehouseServiceServer struct {
}

func (*UnimplementedStorehouseServiceServer) CreateStorehouse(ctx context.Context, req *CreateStorehouseRequest) (*Storehouse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStorehouse not implemented")
}
func (*UnimplementedStorehouseServiceServer) GetStorehousesListByCityId(ctx context.Context, req *GetStorehousesListByCityIdRequest) (*GetStorehousesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorehousesListByCityId not implemented")
}
func (*UnimplementedStorehouseServiceServer) GetItemsByStorehouseId(ctx context.Context, req *GetItemsByStorehouseIdRequest) (*GetItemsByStorehouseIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemsByStorehouseId not implemented")
}
func (*UnimplementedStorehouseServiceServer) CreateItemForStorehouse(ctx context.Context, req *CreateItemForStorehoseRequest) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItemForStorehouse not implemented")
}
func (*UnimplementedStorehouseServiceServer) UpdateItem(ctx context.Context, req *UpdateItemRequest) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItem not implemented")
}
func (*UnimplementedStorehouseServiceServer) DeleteItem(ctx context.Context, req *DeleteItemRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (*UnimplementedStorehouseServiceServer) DeleteStorehouse(ctx context.Context, req *DeleteStorehouseRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStorehouse not implemented")
}

func RegisterStorehouseServiceServer(s *grpc.Server, srv StorehouseServiceServer) {
	s.RegisterService(&_StorehouseService_serviceDesc, srv)
}

func _StorehouseService_CreateStorehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStorehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).CreateStorehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/CreateStorehouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).CreateStorehouse(ctx, req.(*CreateStorehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_GetStorehousesListByCityId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorehousesListByCityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).GetStorehousesListByCityId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/GetStorehousesListByCityId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).GetStorehousesListByCityId(ctx, req.(*GetStorehousesListByCityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_GetItemsByStorehouseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsByStorehouseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).GetItemsByStorehouseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/GetItemsByStorehouseId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).GetItemsByStorehouseId(ctx, req.(*GetItemsByStorehouseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_CreateItemForStorehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemForStorehoseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).CreateItemForStorehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/CreateItemForStorehouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).CreateItemForStorehouse(ctx, req.(*CreateItemForStorehoseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/UpdateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).UpdateItem(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorehouseService_DeleteStorehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStorehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorehouseServiceServer).DeleteStorehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StorehouseService/DeleteStorehouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorehouseServiceServer).DeleteStorehouse(ctx, req.(*DeleteStorehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorehouseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.StorehouseService",
	HandlerType: (*StorehouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStorehouse",
			Handler:    _StorehouseService_CreateStorehouse_Handler,
		},
		{
			MethodName: "GetStorehousesListByCityId",
			Handler:    _StorehouseService_GetStorehousesListByCityId_Handler,
		},
		{
			MethodName: "GetItemsByStorehouseId",
			Handler:    _StorehouseService_GetItemsByStorehouseId_Handler,
		},
		{
			MethodName: "CreateItemForStorehouse",
			Handler:    _StorehouseService_CreateItemForStorehouse_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _StorehouseService_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _StorehouseService_DeleteItem_Handler,
		},
		{
			MethodName: "DeleteStorehouse",
			Handler:    _StorehouseService_DeleteStorehouse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storehouse.proto",
}
