// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

type Storehouse struct {
	ID     int64
	CityID int32
	Name   string
}

type StorehouseItem struct {
	ID           int64
	StorehouseID int32
	ComponentID  int32
	Count        int32
}
